/**
 * @module src/models/database
 * 
 * @description This module defines the ApiDatabase class, which provides methods 
 * for interacting with a SQLite database using the better-sqlite3 library. It includes
 * methods for selecting a user, inserting a user, inserting a generation, and checking 
 * if a user exists in the database. 
 * 
 * The class is designed to manage database connections and execute SQL queries while 
 * ensuring type safety through the use of TypeScript interfaces and types.
 */

import Database, { type Database as DatabaseType } from 'better-sqlite3';

import { type Config } from '../config.ts';
import { type Dictionary, stringifyWithRules } from '../types/types.ts';

import { readFileSync } from 'fs';

/**
 * The RowType type is a union type that represents the possible types of rows that can be stored in the database.
 * It can be either a User or a Generation, which are defined as interfaces below. This type is used to 
 * ensure type safety when working with database records, allowing for flexible handling of different types 
 * of data while maintaining a consistent structure for database operations.
 */
type RowType = User | Generation;
/**
 * The Table type defines the names of the database tables that the ApiDatabase class interacts with.
 */
type Table = 'users' | 'generations';
/**
 * The Operator type defines the logical operators that can be used in SQL queries when selecting 
 * or checking for records in the database.
 */
type Operator = 'AND' | 'OR';

/**
 * The User interface represents the structure of a user record in the database. It includes optional
 * properties such as user_id, name, surname, email, password, and profile_image_path. The user_id is 
 * optional because it is typically auto-generated by the database upon insertion. The other properties 
 * are also optional to allow for flexible querying and insertion of user records.
 */
export interface User extends Dictionary {
  user_id?: number;
  readonly name?: string;
  readonly surname?: string;
  readonly email?: string;
  readonly password?: string;
  profile_image_path?: string;
}

/**
 * The Generation interface represents the structure of a generation record in the database. It includes
 * properties such as operation_id, user_id, uploaded_images_paths, and generated_image_path. The operation_id
 * is optional because it is typically auto-generated by the database upon insertion. The user_id is a required 
 * field that links the generation to a specific user. The uploaded_images_paths is an array of strings that 
 * contains the paths to the images uploaded by the user for the generation process. 
 * 
 * The generated_image_path is an optional string that contains the path to the image generated as a result 
 * of the generation process.
 */
interface Generation extends Dictionary {
  readonly operation_id?: number;
  readonly user_id: number;
  readonly uploaded_images_paths: string[];
  readonly generated_image_path?: string;
}

/**
 * The ApiDatabase class provides methods for interacting with the SQLite database. It includes methods for selecting 
 * a user, inserting a user, inserting a generation, and checking if a user exists in the database. 
 * 
 * The class uses the better-sqlite3 library to manage database connections and execute SQL queries. The constructor 
 * initializes the database connection using the configuration provided, and the checkTables method ensures that 
 * the necessary tables are created in the database if they do not already exist.
 */
export class ApiDatabase {
  /**
   * The config property holds the configuration settings for the database connection, 
   * including the file path to the database and the schema file.
   */
  private readonly config: Config;
  /**
   * The driver property is an instance of the better-sqlite3 Database class, which is used to execute SQL 
   * queries against the SQLite database. It is initialized in the constructor using the file path provided 
   * in the configuration. 
   * 
   * The driver is responsible for managing the database connection and executing queries, making it a 
   * crucial component of the ApiDatabase class.
   */
  private readonly driver: DatabaseType;

  /**
   * Creates a list of equality conditions for a SQL query based on the provided values.
   * This method iterates over the properties of the provided values object, converts each value to a string.
   * 
   * @param values - An object containing the properties and values to be used in the equality conditions.
   * 
   * @returns An array of strings representing the equality conditions for a SQL query.
   */
  private makeQueryEqualities(values: RowType): string[] {
    let equalities = [];

    for (const property of Object.getOwnPropertyNames(values)) {
      const dataProperty = values[property];
      const value = stringifyWithRules(dataProperty);

      equalities.push(`${property} = ${value}`);
    }

    return equalities;
  }

  /**
   * Selects a row from the database based on the provided data and table. 
   * 
   * It constructs a SQL query using the makeQueryEqualities method to create the WHERE clause, 
   * and executes the query using the better-sqlite3 driver. The result is returned as an 
   * object of type T, which extends RowType.
   *
   * @param data - An object containing the properties and values to be used in the 
   * WHERE clause of the SQL query.
   * @param table - The name of the database table from which to select the row.
   * @param operator - The logical operator (AND/OR) to be used in the WHERE clause 
   * of the SQL query.
   * 
   * @returns An object of type T representing the selected row from the database. 
   */
  private selectRow<T extends RowType>(
    data: T, 
    table: Table, 
    operator: Operator
  ): T {
    let equalities = this.makeQueryEqualities(data);
    
    const result = this.driver.prepare(
      `SELECT * FROM ${table} WHERE ${equalities.join(` ${operator} `)}`
    );

    return result.get() as T;
  }

  /**
   * Inserts a row into the database based on the provided data and table.
   * 
   * This method constructs a SQL INSERT statement by iterating over the properties of the provided data object,
   * converting each value to a string using the stringifyWithRules function, and then executing the statement 
   * using the better-sqlite3 driver. The fields and values are dynamically generated based on the properties 
   * of the data object, allowing for flexible insertion of records into the database.
   * 
   * @param data - An object containing the properties and values to be inserted into the database.
   * @param table - The name of the database table into which to insert the row.
   */
  private insertRow<T extends RowType>(data: Omit<T, keyof T>, table: Table): void {
    const fields = [];
    const values = [];

    for (const property of Object.getOwnPropertyNames(data)) {
      // @ts-ignore FIXME: Should be fixed later with typesafe variant. 
      const dataProperty = data[property];
      const value = stringifyWithRules(dataProperty);
      
      fields.push(property);
      values.push(value);
    }

    const statement = this.driver.prepare(
      `INSERT INTO ${table} (${fields.join(', ')}) VALUES (${values.join(', ')})`
    );
    statement.run();
  }

  /**
   * Checks if a row exists in the database based on the provided data and table.
   * 
   * @param row - An object containing the properties and values to be used in the 
   * WHERE clause of the SQL query.
   * @param table - The name of the database table to check for the row.
   * @param operator - The logical operator (AND/OR) to be used in the WHERE clause 
   * of the SQL query.
   * 
   * @returns A boolean indicating whether the row exists in the database.
   */
  private isRowExists<T extends RowType>(
    row: T, 
    table: Table,
    operator: Operator
  ): boolean {
    let equalities = this.makeQueryEqualities(row);
    const query = this.driver.prepare(
      `SELECT 1 FROM ${table} WHERE ${equalities.join(` ${operator} `)}`
    );
  
    return query.get() !== undefined;
  }

  /**
   * Initializes a new instance of the Database class.
   * The constructor takes a Config object as a parameter, which contains the necessary 
   * configuration for connecting to the database. 
   * 
   * It initializes the database connection using the better-sqlite3 library and sets the 
   * journal mode to WAL (Write-Ahead Logging) for improved performance and concurrency.
   * 
   * @param config - A Config object containing the necessary configuration for connecting to the database,
   * including the file path to the database and the schema file.
   */
  public constructor(config: Config) {
    this.config = config;

    this.driver = new Database(this.config.database.file); 
    this.driver.pragma('journal_mode = WAL');
  }

  /**
   * Checks if the necessary tables exist in the database and creates them if they do not.
   * 
   * This method reads the SQL schema from the file specified in the configuration and executes it using the 
   * better-sqlite3 driver. This ensures that the database is properly initialized with the required tables 
   * before any operations are performed.
   * 
   * @throws Will throw an error if the schema file cannot be read or if there is an issue executing the SQL 
   * statements to create the tables.
   */
  public checkTables(): void {
    const initdriverQuery = readFileSync(this.config.database.schema, 'utf-8'); 
    this.driver.exec(initdriverQuery);
  }

  /**
   * Selects a user from the database based on the provided criteria.
   * 
   * This method constructs a SQL query using the makeQueryEqualities method to create the WHERE clause,
   * and executes the query using the better-sqlite3 driver. The result is returned as a User object if found, 
   * otherwise undefined. The operator parameter allows for flexible querying by specifying whether 
   * to use AND or OR logical operators in the WHERE clause of the SQL query.
   * 
   * @param user - An object containing the properties and values to be used in the 
   * WHERE clause of the SQL query.
   * @param operator - The logical operator (AND/OR) to be used in the WHERE clause 
   * of the SQL query.
   * 
   * @returns The user object if found, otherwise undefined.
   */
  public selectUser(user: User, operator: Operator = 'AND'): User {
    return this.selectRow<User>(user, 'users', operator);
  }

  /**
   * Inserts a new user into the database.
   * 
   * This method constructs a SQL INSERT statement by iterating over the properties of the provided user object,
   * converting each value to a string using the stringifyWithRules function, and then executing the statement 
   * using the better-sqlite3 driver. The fields and values are dynamically generated based on the properties
   * of the user object, allowing for flexible insertion of user records into the database. The user_id and 
   * profile_image_path properties are omitted from the user parameter as they are typically auto-generated by 
   * the database or can be set to default values.
   * 
   * @param user - An object containing the properties and values for the new user. 
   * The user_id and profile_image_path properties are omitted as they are typically 
   * auto-generated by the database or can be set to default values.
   * 
   * @throws Will throw an error if there is an issue executing the SQL statement to insert the new user into the database. 
   */
  public insertUser(user: Omit<User, 'user_id' | 'profile_image_path'>): void {
    this.insertRow<User>(user, 'users');
  }

  /**
   * Inserts a new generation into the database.
   * This method constructs a SQL INSERT statement by iterating over the properties of the provided 
   * generation object, converting each value to a string using the stringifyWithRules function, and 
   * then executing the statement using the better-sqlite3 driver. The fields and values are dynamically 
   * generated based on the properties of the generation object, allowing for flexible insertion of 
   * generation records into the database. The operation_id property is omitted from the generation 
   * parameter as it is typically auto-generated by the database. 
   * 
   * @param generation - An object containing the properties and values for the new generation. 
   * The operation_id property is omitted as it is typically auto-generated by the database.
   * 
   * @throws Will throw an error if there is an issue executing the SQL statement to insert the 
   * new generation into the database.
   */
  public insertGeneration(
    generation: Omit<Generation, 'operation_id'>
  ): void {
    this.insertRow<Generation>(generation, 'generations');
  }

  /**
   * Checks if a user exists in the database based on the provided criteria.
   * 
   * This method constructs a SQL query using the makeQueryEqualities method to create the WHERE clause,
   * and executes the query using the better-sqlite3 driver. It returns a boolean indicating whether the 
   * user exists in the database. The operator parameter allows for flexible querying by specifying whether
   * to use AND or OR logical operators in the WHERE clause of the SQL query. This method is useful for
   * validating user credentials during login or checking for the existence of a user before performing 
   * certain operations.
   * 
   * @param user - An object containing the properties and values to be used in the 
   * WHERE clause of the SQL query.
   * @param operator - The logical operator (AND/OR) to be used in the WHERE clause 
   * of the SQL query.
   * 
   * @returns A boolean indicating whether the user exists.
   */
  public isUserExists(user: User, operator: Operator = 'AND'): boolean {
    return this.isRowExists(user, 'users', operator);
  }
}
